kernel-dev: Fix syntax error in linux-windriver_3.10 recipe
Issue: LIN7-391

sysroot_stage_all is python function in kernel.bbclass, so
sysroot_stage_all_append should follow the python syntax with 4 white spaces
indentation instead of tab and rewrite it to python function.
Otherwise, the below syntax error is caught when include kernel-dev layer:

ERROR: ExpansionError during parsing layers/wr-kernel/recipes-kernel/linux/linux-windriver_3.10.bb:
Failure expanding variable sysroot_stage_all: IndentationError: unexpected indent (<string>, line 3)

Signed-off-by: Yang Shi <yang.shi@windriver.com>